// "use client";

// import React, { useEffect, useState } from "react";
// import axios from "axios";
// import { 
//   MapPin, 
//   Calendar, 
//   ArrowRight, 
//   Sparkles, 
//   Star, 
//   TrendingUp,
//   ChevronRight
// } from "lucide-react";
// import Link from "next/link";

// export default function PopularTrips() {
//   const [trips, setTrips] = useState<any[]>([]);
//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     const fetchPopularTrips = async () => {
//       try {
//         setLoading(true);
//         // নোট: এখানে আপনার ব্যাকএন্ডের এপিআই কল করুন
//         const response = await axios.get(`http://localhost:5000/api/v1/ai/my-trips`);
//         if (response.data.success) {
//           // পপুলার দেখানোর জন্য আমরা প্রথম ৩টি বা ৬টি ট্রিপ স্লাইস করছি
//           setTrips(response.data.data.slice(0, 3)); 
//         }
//       } catch (err) {
//         console.error("Error fetching popular trips:", err);
//       } finally {
//         setLoading(false);
//       }
//     };
//     fetchPopularTrips();
//   }, []);

//   if (loading) return <PopularTripsSkeleton />;

//   return (
//     <section className="py-32 bg-slate-50 dark:bg-slate-950/50 overflow-hidden">
//       <div className="max-w-7xl mx-auto px-6">
        
//         {/* সেকশন হেডার */}
//         <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-16 gap-8">
//           <div className="space-y-6">
//             <div className="inline-flex items-center gap-2 px-5 py-2 bg-blue-600/10 border border-blue-600/20 rounded-full">
//               <TrendingUp size={16} className="text-blue-600" />
//               <span className="text-[10px] font-black text-blue-600 uppercase tracking-[0.2em]">Trending Now</span>
//             </div>
//             <h2 className="text-5xl md:text-7xl font-black text-slate-900 dark:text-white tracking-tighter uppercase leading-[0.85]">
//               Explore <br /> <span className="text-blue-600">Popular Trips</span>
//             </h2>
//             <p className="max-w-md text-slate-500 font-medium text-lg">
//               Handpicked adventures generated by our AI, loved by travelers worldwide.
//             </p>
//           </div>
          
//           <Link href="/dashboard/my-trips" className="group flex items-center gap-4 px-8 py-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl font-black text-xs uppercase tracking-widest shadow-xl shadow-slate-200/50 dark:shadow-none transition-all hover:scale-105">
//             View All Journeys <ChevronRight size={18} className="group-hover:translate-x-1 transition-transform" />
//           </Link>
//         </div>

//         {/* ট্রিপ কার্ড গ্রিড */}
//         <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
//           {trips.map((trip, idx) => (
//             <div 
//               key={trip._id} 
//               className="group relative flex flex-col bg-white dark:bg-slate-900 rounded-[3.5rem] p-4 border border-slate-100 dark:border-slate-800 transition-all duration-500 hover:shadow-2xl hover:shadow-blue-500/10 hover:-translate-y-3"
//             >
//               {/* কার্ড ইমেজ এরিয়া (কালার গ্রেডিয়েন্ট) */}
//               <div className="relative h-72 w-full rounded-[2.8rem] overflow-hidden bg-slate-100 dark:bg-slate-800">
//                 <div className={`absolute inset-0 bg-gradient-to-br ${
//                   idx === 0 ? 'from-blue-600 to-indigo-900' : 
//                   idx === 1 ? 'from-emerald-500 to-teal-900' : 
//                   'from-rose-500 to-orange-900'
//                 } opacity-90 transition-transform duration-700 group-hover:scale-110`} />
                
//                 <div className="absolute inset-0 flex flex-col items-center justify-center p-8 text-center text-white">
//                   <MapPin className="mb-4 opacity-50" size={32} />
//                   <h3 className="text-3xl font-black uppercase tracking-tighter leading-none mb-2">
//                     {trip.destination}
//                   </h3>
//                   <div className="px-4 py-1.5 bg-white/10 backdrop-blur-md border border-white/20 rounded-full text-[10px] font-black uppercase tracking-widest">
//                     {trip.budget} Budget
//                   </div>
//                 </div>

//                 {/* এআই ব্যাজ */}
//                 <div className="absolute top-6 left-6 flex items-center gap-2 px-3 py-1.5 bg-black/20 backdrop-blur-lg rounded-full text-[8px] font-black text-white uppercase tracking-widest border border-white/10">
//                   <Sparkles size={10} /> AI Optimized
//                 </div>
//               </div>

//               {/* কার্ড কন্টেন্ট */}
//               <div className="p-8 space-y-6">
//                 <div className="flex justify-between items-center">
//                   <div className="flex items-center gap-2 text-slate-400 font-black text-[10px] uppercase tracking-widest">
//                     <Calendar size={14} className="text-blue-600" /> {trip.days} Days
//                   </div>
//                   <div className="flex items-center gap-1 text-yellow-500">
//                     <Star size={14} fill="currentColor" />
//                     <span className="text-[10px] font-black text-slate-900 dark:text-white uppercase">4.9</span>
//                   </div>
//                 </div>

//                 <p className="text-slate-500 dark:text-slate-400 text-sm font-medium leading-relaxed line-clamp-2 italic">
//                   Explore the hidden gems of {trip.destination} with our custom-built itinerary designed for maximum adventure.
//                 </p>

//                 <div className="pt-6 border-t border-slate-50 dark:border-slate-800 flex items-center justify-between">
//                   <div className="flex flex-col">
//                     <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest">Starting from</span>
//                     <span className="text-xl font-black text-slate-900 dark:text-white tracking-tighter italic">Explore Now</span>
//                   </div>
//                   <Link 
//                     href={`/dashboard/my-trips/${trip._id}`}
//                     className="w-14 h-14 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-[1.5rem] flex items-center justify-center transition-all hover:bg-blue-600 dark:hover:bg-blue-600 dark:hover:text-white group-hover:rotate-[-45deg]"
//                   >
//                     <ArrowRight size={24} />
//                   </Link>
//                 </div>
//               </div>
//             </div>
//           ))}
//         </div>
//       </div>
//     </section>
//   );
// }

// function PopularTripsSkeleton() {
//   return (
//     <div className="py-32 max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-10">
//       {[1, 2, 3].map((i) => (
//         <div key={i} className="h-[600px] bg-slate-100 dark:bg-slate-900 animate-pulse rounded-[3.5rem]" />
//       ))}
//     </div>
//   );
// }

"use client";

import React, { useEffect, useState } from "react";
import axios from "axios";
import { 
  MapPin, Calendar, Star, ArrowRight, Sparkles, ChevronRight 
} from "lucide-react";
import Link from "next/link";

export default function PopularTrips() {
  const [trips, setTrips] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchTrips = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`http://localhost:5000/api/v1/ai/all-trips`);
        if (response.data.success) {
          setTrips(response.data.data.slice(0, 8));
        }
      } catch (err) {
        console.error("Error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchTrips();
  }, []);

  if (loading) return <PopularTripsSkeleton />;

  // লাইট মোডে কালার প্যালেট (Dhaka Style - Vibrant)
  const lightGradients = [
    "from-blue-400 to-indigo-500",
    "from-emerald-400 to-teal-500",
    "from-rose-400 to-orange-500",
    "from-violet-400 to-purple-500"
  ];

  // ডার্ক মোডে কালার প্যালেট (Kuakata Style - Deep)
  const darkGradients = [
    "dark:from-blue-600 dark:to-indigo-900",
    "dark:from-emerald-600 dark:to-teal-900",
    "dark:from-rose-600 dark:to-orange-900",
    "dark:from-violet-600 dark:to-purple-900"
  ];

  return (
    <section className="py-24 bg-white dark:bg-[#020617] transition-colors duration-500">
      <div className="max-w-7xl mx-auto px-6">
        
        {/* Header */}
        <div className="mb-16 text-left space-y-4">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-blue-600/10 border border-blue-600/20 rounded-full">
            <Sparkles size={14} className="text-blue-600" />
            <span className="text-[10px] font-black text-blue-600 uppercase tracking-widest">Trending Now</span>
          </div>
          <h2 className="text-5xl md:text-7xl font-black text-slate-900 dark:text-white tracking-tighter uppercase leading-[0.85]">
            Popular <span className="text-blue-600">Trips</span>
          </h2>
        </div>

        {/* Dynamic Card Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 mb-20">
          {trips.map((trip, idx) => (
            <div 
              key={trip._id} 
              className="group relative flex flex-col h-full transition-all duration-500 
                /* Card Body */
                bg-white dark:bg-slate-900/50 
                border border-slate-200 dark:border-blue-500/20 
                shadow-xl shadow-slate-200/50 dark:shadow-none
                rounded-[3rem] p-4 hover:-translate-y-3 hover:shadow-2xl"
            >
              {/* Image/Gradient Area - এখানেই কালার ফিক্স করা হয়েছে */}
              <div className="relative h-52 w-full rounded-[2.5rem] overflow-hidden shadow-inner mb-6">
                {/* Background Gradient - Light & Dark উভয়ের জন্যই কালারফুল */}
                <div className={`absolute inset-0 bg-gradient-to-br 
                  ${lightGradients[idx % 4]} 
                  ${darkGradients[idx % 4]} 
                  opacity-100 transition-transform duration-700 group-hover:scale-110`} 
                />
                
                {/* Content over gradient */}
                <div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center text-white">
                  <MapPin className="mb-3 opacity-70" size={28} />
                  <h3 className="text-2xl font-black uppercase tracking-tighter leading-none mb-2 drop-shadow-md">
                    {trip.destination}
                  </h3>
                  <div className="px-3 py-1 bg-white/20 backdrop-blur-md border border-white/30 rounded-full text-[8px] font-black uppercase tracking-widest">
                    {trip.budget} Budget
                  </div>
                </div>

                <div className="absolute top-4 left-4 flex items-center gap-2 px-3 py-1.5 bg-black/10 backdrop-blur-md rounded-full text-[7px] font-black text-white uppercase tracking-widest border border-white/10">
                  <Sparkles size={10} /> AI Generated
                </div>
              </div>

              {/* Text Content */}
              <div className="px-4 pb-6 flex flex-col flex-grow space-y-4">
                <div className="flex justify-between items-center text-[10px] font-black uppercase tracking-widest">
                  <div className="flex items-center gap-1.5 text-slate-400">
                    <Calendar size={14} className="text-blue-600" /> {trip.days} Days
                  </div>
                  <div className="flex items-center gap-1 text-yellow-500">
                    <Star size={12} fill="currentColor" /> 4.9
                  </div>
                </div>

                <p className="text-sm text-slate-500 dark:text-slate-400 font-medium italic line-clamp-2">
                   Explore {trip.destination} with a budget-friendly {trip.budget} plan.
                </p>

                <Link 
                  href={`/public-trips/${trip._id}`}
                  className="w-full py-4 bg-slate-900 dark:bg-blue-600 text-white rounded-2xl flex items-center justify-center gap-2 font-black text-[10px] uppercase tracking-widest transition-all hover:bg-blue-600 dark:hover:bg-blue-500 shadow-lg shadow-blue-500/20"
                >
                  View Details <ArrowRight size={16} />
                </Link>
              </div>
            </div>
          ))}
        </div>

        {/* Explore All Button */}
        <div className="flex justify-center">
          <Link 
            href="/explore" 
            className="group flex items-center gap-4 px-12 py-5 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-full font-black text-xs uppercase tracking-[0.2em] transition-all hover:scale-105 shadow-2xl shadow-blue-500/10"
          >
            Explore All Journeys
            <ChevronRight size={20} className="group-hover:translate-x-1 transition-transform" />
          </Link>
        </div>

      </div>
    </section>
  );
}

function PopularTripsSkeleton() {
  return (
    <div className="py-24 max-w-7xl mx-auto px-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
      {[...Array(8)].map((_, i) => (
        <div key={i} className="h-96 bg-slate-100 dark:bg-slate-800 animate-pulse rounded-[3rem]" />
      ))}
    </div>
  );
}